### PR TITLE
Make goid compatible with go1.9

### PR DESCRIPTION
**Pull request by ggaaooppeenngg**
Based on issues below, some fields are removed from g.

https://go-review.googlesource.com/c/36621/
https://go-review.googlesource.com/c/36620/

Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>

### CODE REVIEW

**Comment by tamird** [comment]
Thank you for the PR! Would you mind adding `master` to `.travis.yml`? See https://docs.travis-ci.com/user/languages/go/.

**Comment by tamird** [comment]
@ggaaooppeenngg I made some changes to `.travis.yml` before my last comment, looks like you're getting a merge conflict as a result. Could you rebase please?

**Comment by ggaaooppeenngg** [comment]
@tamird  done

**Comment by tamird** [comment]
Thank you @ggaaooppeenngg!

**Pull request merged**
